config/routes.rb
Rails.application.routes.draw do

  resources :boards, only: [:show] do
  	resources :links, only: [:create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
	has_many :links
end

app/models/link.rb
class Link < ApplicationRecord
	belongs_to :board

  after_create :notify_created

  def notify_created
    connection = ActiveRecord::Base.connection
    connection.execute "NOTIFY #{channel}, #{connection.quote self.id.to_s}"
  end

  private
  def channel
    "board_#{self.board.id}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	def show
		@board = Board.find(params[:id])
		@links = @board.links
		@link = Link.new
	end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include ActionController::Live

  def index
    response.headers['Content-Type'] = 'text/event-stream'

    sse = SSE.new(response.stream)

    begin
      on_link_created do |link_id|
        puts "Received Link created event"
        link = Link.find(link_id)

        sse.write({data: link.as_json}, event: "newlink")
      end
    rescue IOError
      puts "Client Disconnected"
    ensure
      puts "SSE is Closing"
      sse.close
    end

    render nothing: true
  end

	def create
    link = Link.create!(links_params)

    respond_to do |format|
      if link.persisted?
        format.json {render json: link}
      else
        format.json {render json: { error_message: "Didn't work" }, status: :unprocessable_entity}
      end
    end
  end

  private

  def on_link_created
    connection = ActiveRecord::Base.connection
    connection.execute "LISTEN #{channel}"

    connection.raw_connection.wait_for_notify do |event, pid, link|
      yield link
    end
  ensure
    puts "Unlistening from channel"
    connection.execute "UNLISTEN #{channel}"
  end

  def links_params
    merged_params = {}
    # This is throwing deprecation warning because of #to_hash. Should use #to_h instead
    merged_params.merge! params.permit(:board_id)
    merged_params.merge! params.require(:link).permit(:url)

    merged_params
  end

  # Creation of link associated with board x should broadcast an event
  # on channel board_x
  def channel
    "board_#{params[:board_id]}"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/boards/show.html.erb
<h1 data-board-id="<%= @board.id %>" class="board-title h5"><%= @board.id  %></h1>

<div class="link-drop-zone h1 alternative-font-color">
  <p class="link-drop-zone-text">Drop a link here</p>
</div>

<%= form_for(@link, remote: true, url: board_links_path(@board)) do |f| %>
 <%= f.text_field :url %>
 <%= f.submit "Add" %>
<% end %>

<ul class="link-list">
  <% @links.each do |link| %>
		<li class="link"><%= link.url %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinkBoard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>